# Generated by Django 5.0.6 on 2024-05-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('fonction', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
