# Generated by Django 5.0.6 on 2024-05-26 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, null=True)),
                ('libelle', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cate_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, null=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.about')),
            ],
        ),
    ]
